---
- name: Create Azure Resource Group
  azure_rm_resourcegroup:
    name: "{{ globalau.resourcegroup }}"
    location: "{{ globalau.region }}"
    state: "{{ globalau.state }}"
    force_delete_nonempty: "{{ globalau.force_delete_nonempty }}"
