---
- name: Create Azure Resource Group
  azure_rm_resourcegroup:
    name: "{{ globaluk.resourcegroup }}"
    location: "{{ globaluk.region }}"
    state: "{{ globaluk.state }}"
    force_delete_nonempty: "{{ globaluk.force_delete_nonempty }}"
