#!/usr/bin/ansible-playbook
#
# Main Azure infrastructure deployment playbook
#
---
- hosts: localhost
  vars_files:
  - az_setup_vars.yaml
  tasks:
  - import_tasks: tasks/AU/vnet/create_rg.yaml
    tags: [ rg ]
  - import_tasks: tasks/AU/vnet/create_vnet.yaml
    tags: [ vnet ]
  - import_tasks: tasks/UK/vnet/create_rg.yaml
    tags: [ rg ]
  - import_tasks: tasks/UK/vnet/create_vnet.yaml
    tags: [ vnet ]
